### connection details
ansible_host: 192.168.0.42
ansible_user: root
ansible_ssh_password: somethingsecure


#db_user: "{{ vault_db_user_db-host }}"
#db_password: "{{ vault_db_password_db-host }}"

db_user: mydb_user
db_password: mydb_user_pass

db_list:
  - db1
  - db2
  - db3
